# Generated by Django 3.0.3 on 2020-02-24 17:14

from django.db import migrations, models, transaction
import pandas as pd
from datetime import datetime
import pytz


@transaction.atomic
def load_initial_data(apps, schema_editor):
    Rating = apps.get_model("movie_rec", "Rating")
    Movie = apps.get_model("movie_rec", "Movie")

    df_movies = pd.read_csv('data/movies.csv')
    df_ratings = pd.read_csv('data/ratings.csv')

    movies = []
    ratings = []

    for _, row in df_movies.iterrows():
        movie = Movie(
            id=row['movieId'],
            title=row['title'],
            genres=row['genres']
        )
        movies.append(movie)

    for _, row in df_ratings.iterrows():
        rating = Rating(
            user_id=row['userId'],
            movie_id=row['movieId'],
            rating=int(row['rating']),
            timestamp=datetime.utcfromtimestamp(
                row['timestamp']).replace(tzinfo=pytz.utc)
        )
        ratings.append(rating)

    Movie.objects.bulk_create(movies)
    Rating.objects.bulk_create(ratings)


@transaction.atomic
def reverse_func(apps, schema_editor):
    Rating = apps.get_model("movie_rec", "Rating")
    Movie = apps.get_model("movie_rec", "Movie")

    Rating.objects.all().delete()
    Movie.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rec', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
